### ISSUE TITLE
No graceful handling of empty MessageAttributes

### ISSUE THREAD

**Issue by steve-hb** [udhos/opentelemetry-trace-sqs#2]
Hi,

During our first tests, we noticed the runtime to panic when the MessageAttributes are not set beforehand.
In our use-case we did not need any attributes, therefore our code did not set them.

https://github.com/udhos/opentelemetry-trace-sqs/blob/30262ab49936445ce6f4213c2291d1e9bfe934ed/otelsqs/otelsqs.go#L121C2-L121C3

Proposal: Handle this case gracefully by using an empty slice. I would also create a PR for this if found useful.

Is there any downside you can think of?

Best Regards,
Steve

**Comment by udhos** [comment]
Hi

I dont see a strong reason against improving the package so that the Inject() methods would withstand nil maps.

The initial design relied on the documentation to make clear that the Inject() methods require non-nil maps.

I guess that supporting nil maps would make the lib easier to use, and that would add a little complexity overall (ie at least more test cases covering nil maps).

It would gladly consider such PR.

**Comment by udhos** [comment]
Hi,

I have released [v1.3.0](https://github.com/udhos/opentelemetry-trace-sqs/commit/96d128566167f0ae3cb9d1b81f91cd6ee82e758c) with Inject() methods returning error instead of panic, for nil maps, in order to signal that the requested operation did not complete.

It does not look much better, but it gives more control to the caller, at the added risk of the caller failing to realize the Inject() method might have failed.
